version: "3.7"

services:
  app:
    container_name: golden-app
    build: .
    ports:
    - 8080:8080
    environment:
    - GOLDEN_DB_URL=devops22.cehxjqytwbqs.us-east-1.rds.amazonaws.com
    - GOLDEN_DB_NAME=goldendb
    - GOLDEN_DB_USERNAME=admin
    - GOLDEN_DB_PASSWORD=DevOps2022
    - GOLDEN_DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    networks:
    - goldenwaste-network

  db:
    container_name: goldenwastesqldb
    image: mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: DevOps2022
      MYSQL_DATABASE: goldenwaste
    volumes:
    - goldenwaste-mysql:/var/lib/mysql
    - goldenwaste-mysql-config:/etc/mysql
    networks:
    - goldenwaste-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10